### ISSUE TITLE
Strukturera dokumentationen

### ISSUE THREAD

**Issue by mosbth** [litemerafrukt/dbstream_dokumentation#1]
Lägg projektrelaterat i en katalog och produktrelaterat i en underkatalog.
Försök göra det tydligt så man enkelt kan hitta när allt fler dokument kommer till.

**Comment by litemerafrukt** [comment]
Projektrelaterade dokument hittas numera i [projekt](https://github.com/litemerafrukt/dbstream_dokumentation/tree/master/projekt).
